# Configuração do datasource (H2 in-memory por padrão no modo dev)
quarkus.datasource.db-kind=h2
quarkus.datasource.username=sa  # Usuário padrão do H2
quarkus.datasource.password=   # Senha vazia por padrão

# JDBC URL para H2 in-memory (banco é criado automaticamente e executa apenas em memória)
#quarkus.datasource.jdbc.url=jdbc:h2:mem:default;DB_CLOSE_DELAY=-1

# URL persistente: cria/salva em um arquivo no disco
quarkus.datasource.jdbc.url=jdbc:h2:./target/h2-database/escola-db;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1

# Configurações do Hibernate ORM
# Cria as tabelas automaticamente no startup (ideal para dev)
#quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.database.generation=update

# Mostra os SQLs no console para debug
quarkus.hibernate-orm.log.sql=true  

# Para modo dev, o Quarkus já ativa o H2 console em /q/h2-console (acesso via browser)
quarkus.hibernate-orm.sql-load-script=import.sql

#Para acessar swagger e H2 no browser
